FROM lefilament/odoo:{{ odoo_version }}{% if odoo_multilingual is defined and odoo_multilingual %}_ml{% endif %}

MAINTAINER Le Filament <https://le-filament.com>

USER root 
{% if odoo_pip_packages is defined %}
# Install pip packages
RUN pip install {{ odoo_pip_packages }}
{% endif %}
{% if git_private_keys is defined %}
# Install private keys
COPY ./id_rsa ~root/.ssh/
{% endif %}
# Install private repos
COPY ./private/* /opt/odoo/private/
RUN /opt/odoo/private/fetch_repos_addons
RUN /opt/odoo/private/fetch_repos

# Copy Odoo configuration file
COPY ./odoo.conf /opt/odoo/etc/odoo.conf
RUN chown odoo:odoo /opt/odoo/etc/odoo.conf

USER odoo
