FROM index.docker.io/tecnativa/duplicity:postgres
RUN apk add --no-cache --virtual .build \
        build-base \
        krb5-dev \
        libffi-dev \
        librsync-dev \
        libxml2-dev \
        libxslt-dev \
        openssl-dev \
    # Runtime dependencies, based on https://bazaar.launchpad.net/~duplicity-team/duplicity/0.8-series/view/head:/requirements.txt
    && pip install --no-cache-dir \
        # Basic dependencies
        python-keystoneclient \
    && apk del .build
