#!/usr/bin/env python
# -*- coding: utf-8 -*-
import grp
import os
import pwd
import shutil
import yaml
from subprocess import call

DEFAULT_PRIVATE_REPO="/opt/odoo/private_addons"
REPO_FILE="/opt/odoo/private/repos.yaml"
UID = pwd.getpwnam("odoo").pw_uid
GID = grp.getgrnam("odoo").gr_gid

if os.path.isfile(REPO_FILE):
    repos = yaml.safe_load(open(REPO_FILE))
    if repos:
        for repo in repos:
            call(["git","clone","-b","10.0","--depth","1",repos[repo],DEFAULT_PRIVATE_REPO+"/"+repo])

        for root, dirs, files in os.walk(DEFAULT_PRIVATE_REPO):
            for target in dirs + files:
                os.chown(os.path.join(root, target), UID, GID)

